name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
          build_type: [Release, Debug]
          # clang++ works with version 15 which is not available on 22.04 yet
          cxx_compiler: [g++]
    
    steps:
      - name: Ubuntu apt install deps
        run: sudo apt-get install -qy libpcap-dev build-essential cmake gcc g++ # clang

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure CMake for ${{matrix.cxx_compiler}}
        run: CXX=${{matrix.cxx_compiler}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure --progress
